### ISSUE TITLE
Replace Java bytecode error in MethodVisitor

### ISSUE THREAD

**Issue by KatatsumuriPan** [CleanroomMC/ModularUI#33]
The exception is thrown:(indev)
```
Caused by: java.lang.NoSuchMethodError: net.minecraft.network.PacketBuffer.writeVarInt(I)Lio/netty/buffer/ByteBuf;
	at net.minecraft.network.PacketBuffer.writeItemStack(PacketBuffer.java:365)
	at net.minecraftforge.fml.common.network.ByteBufUtils.writeItemStack(ByteBufUtils.java:180)
```
(Also the exception is thrown in runtime.)

The method descriptor of "writeVarInt" is "(I)Lnet.minecraft.network.PacketBuffer;" , not "(I)Lio/netty/buffer/ByteBuf;".
Should replace the desc in https://github.com/CleanroomMC/ModularUI/blob/e6883184154a3567deda73325fb57a35966f037d/src/main/java/com/cleanroommc/modularui/core/visitor/PacketByteBufferVisitor.java#L44-L46, taking care of the obfuscated class name of "net.minecraft.network.PacketBuffer".

**Comment by brachy84** [comment]
woops

**Comment by brachy84** [comment]
fixed in latest commit

**Comment by KatatsumuriPan** [comment]
thanks!
