### ISSUE TITLE
NetworkDispatcher exception

### ISSUE THREAD

**Issue by Avalanche7CZ** [CleanroomMC/ModularUI#6]
Your mod messing up with packets
Version: modularui-1.0.6
Forge: 14.23.5.2860
Full log: https://paste.gg/p/anonymous/f7201729ffd64b60a3b7de43996b70f1

```
20:31:24] [Client thread/INFO]: [CHAT] [AC]  Please, login with the command: /login <password>
--
  | [20:31:26] [Client thread/INFO]: [CHAT] [AC]  Successful login!
  | [20:31:27] [Netty Client IO #9/ERROR]: NetworkDispatcher exception
  | io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(10) + length(1) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 10, widx: 10, cap: 10/10)
  | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
  | Caused by: java.lang.IndexOutOfBoundsException: readerIndex(10) + length(1) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 10, widx: 10, cap: 10/10)
  | at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
  | at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864) ~[gy.class:?]
  | at net.minecraft.network.PacketBuffer.readVarInt(PacketBuffer.java:201) ~[gy.class:?]
  | at net.minecraft.network.play.server.SPacketSetSlot.handler$zbo000$readPacketData(SourceFile:522) ~[iu.class:?]
  | at net.minecraft.network.play.server.SPacketSetSlot.readPacketData(SourceFile:38) ~[iu.class:?]
  | at net.minecraft.network.NettyPacketDecoder.decode(SourceFile:40) ~[gz.class:?]
  | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
  | ... 31 more
```

**Comment by Avalanche7CZ** [comment]
Paper shit, server works as auth/lobby

**Comment by Avalanche7CZ** [comment]
You need
Velocity 3.1.2-SNAPSHOT (git-7d77bfb5-b184)
Paper version git-Paper-218 (MC: 1.18.2)  (Lobby server) with ViaVersion, ViaRewind, ViaBackwards plugins

And try to connect to lobby server.

**Comment by Irgendwer01** [comment]
@Avalanche7CZ Since you're using an Hybrid, atleast tell us which Hybrid you are using, and please give the latest.log of the Server too. And in most cases it's the Hybrid's fault, **not** from the mod.

**Comment by Avalanche7CZ** [comment]
@Irgendwer01 
**Paper version git-Paper-218 (MC: 1.18.2**
Here is latest.log from the server:
https://paste.gg/p/anonymous/987de850dbbb4c5c8260fa4ef0d415aa

it just says I've disconnected. (Avalanche7CZ)

Velocity log
https://paste.gg/p/anonymous/0d8d61188a98477bb8b2a41d8685e366

**Comment by brachy84** [comment]
probably fixed in mui2
